name: Test Generated Rust

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: (cd fiat-rust; cargo build --verbose)
    - name: Run tests
      run: (cd fiat-rust; cargo test --verbose)
